"use client";import{useEffect,useRef,useState}from"react";
type Props={src:string|null;nextSrc:string|null;playing:boolean;currentBpm?:number;nextBpm?:number;onEnded:()=>void};
export default function AudioPlayer({src,nextSrc,playing,currentBpm,nextBpm,onEnded}:Props){
 const aRef=useRef<HTMLAudioElement>(null),bRef=useRef<HTMLAudioElement>(null),active=useRef<0|1>(0),loaded=useRef(""),timer=useRef<number|null>(null),transitioning=useRef(false),endRef=useRef(onEnded);
 const ctx=useRef<AudioContext|null>(null),gainA=useRef<GainNode|null>(null),gainB=useRef<GainNode|null>(null),[error,setError]=useState("");endRef.current=onEnded;
 const audio=()=>active.current===0?aRef.current:bRef.current;
 const ensureGraph=()=>{if(ctx.current)return;const C=window.AudioContext||(window as any).webkitAudioContext;if(!C)throw new Error("Web Audio is not supported");const c=new C();ctx.current=c;const aa=aRef.current!,bb=bRef.current!,ga=c.createGain(),gb=c.createGain();c.createMediaElementSource(aa).connect(ga).connect(c.destination);c.createMediaElementSource(bb).connect(gb).connect(c.destination);ga.gain.value=1;gb.gain.value=0;gainA.current=ga;gainB.current=gb};
 useEffect(()=>{const a=aRef.current;if(!a||!src)return;const path=src.split("?")[0];if(loaded.current!==path){loaded.current=path;transitioning.current=false;a.src=src;a.load();if(playing)a.play().catch(e=>setError(e?.message||"Playback was blocked."))}},[src,playing]);
 useEffect(()=>{const a=audio();if(!a)return;if(playing){try{ensureGraph();ctx.current?.resume()}catch(e){setError(e instanceof Error?e.message:"Web Audio unavailable")}if(a.paused)a.play().catch(e=>setError(e?.message||"Playback was blocked."))}else{a.pause();aRef.current?.pause();bRef.current?.pause()}},[playing]);
 useEffect(()=>{const clear=()=>{if(timer.current)window.clearTimeout(timer.current);timer.current=null};const a=audio();if(!a||!src||!nextSrc||transitioning.current)return;const schedule=()=>{clear();const bpm=currentBpm&&currentBpm>0?currentBpm:120;const fade=Math.min(12,Math.max(6,(60/bpm)*8));const delay=Math.max(0,(a.duration||0)-a.currentTime-fade);timer.current=window.setTimeout(()=>startTransition(fade),delay*1000)};const startTransition=(fade:number)=>{if(transitioning.current||!nextSrc)return;const from=audio(),to=active.current===0?bRef.current:aRef.current;if(!from||!to)return;transitioning.current=true;try{ensureGraph();ctx.current?.resume();to.src=nextSrc;to.load();to.playbackRate=currentBpm&&nextBpm?Math.max(.94,Math.min(1.06,currentBpm/nextBpm)):1;const p=to.play();if(p)p.catch(e=>{setError(e?.message||"Next track could not start");transitioning.current=false;return});const now=ctx.current?.currentTime||0,gFrom=active.current===0?gainA.current:gainB.current,gTo=active.current===0?gainB.current:gainA.current;gFrom?.gain.cancelScheduledValues(now);gTo?.gain.cancelScheduledValues(now);gFrom?.gain.setValueAtTime(1,now);gTo?.gain.setValueAtTime(0,now);gFrom?.gain.linearRampToValueAtTime(0,now+fade);gTo?.gain.linearRampToValueAtTime(1,now+fade);window.setTimeout(()=>{from.pause();from.currentTime=0;active.current=active.current===0?1:0;loaded.current=nextSrc.split("?")[0];transitioning.current=false;endRef.current()},fade*1000)}catch(e){setError(e instanceof Error?e.message:"Transition failed");transitioning.current=false}};if(Number.isFinite(a.duration)&&a.duration>0)schedule();else a.addEventListener("loadedmetadata",schedule,{once:true});return clear},[src,nextSrc,currentBpm,nextBpm]);
 useEffect(()=>{return()=>{if(timer.current)window.clearTimeout(timer.current);ctx.current?.close()}},[]);
 return <div>{error&&<div style={{color:"#ff7777",fontSize:11,marginBottom:6}}>{error}</div>}<audio ref={aRef} controls preload="metadata" playsInline className="audio-player"/><audio ref={bRef} preload="metadata" playsInline style={{display:"none"}}/></div>
}