"use client";import{useEffect,useRef,useState}from"react";
type Props={src:string|null;nextSrc:string|null;playing:boolean;currentBpm?:number;nextBpm?:number;currentBeat?:number;nextBeat?:number;nextFirstBeat?:number;currentEnergy?:number;nextEnergy?:number;onEnded:()=>void};
export default function AudioPlayer({src,nextSrc,playing,currentBpm,nextBpm,currentBeat,nextBeat,nextFirstBeat,currentEnergy,nextEnergy,onEnded}:Props){
 const aRef=useRef<HTMLAudioElement>(null),bRef=useRef<HTMLAudioElement>(null),active=useRef<0|1>(0),loaded=useRef(""),timer=useRef<number|null>(null),transitioning=useRef(false),endRef=useRef(onEnded);
 const ctx=useRef<AudioContext|null>(null),gainA=useRef<GainNode|null>(null),gainB=useRef<GainNode|null>(null),bassA=useRef<BiquadFilterNode|null>(null),bassB=useRef<BiquadFilterNode|null>(null),[error,setError]=useState("");endRef.current=onEnded;
 const audio=()=>active.current===0?aRef.current:bRef.current;
 const ensureGraph=()=>{if(ctx.current)return;const C=window.AudioContext||(window as any).webkitAudioContext;if(!C)throw new Error("Web Audio is not supported");const c=new C();ctx.current=c;const aa=aRef.current!,bb=bRef.current!,ga=c.createGain(),gb=c.createGain(),ba=c.createBiquadFilter(),bbf=c.createBiquadFilter();ba.type="lowshelf";ba.frequency.value=140;bbf.type="lowshelf";bbf.frequency.value=140;aa&&c.createMediaElementSource(aa).connect(ba).connect(ga).connect(c.destination);bb&&c.createMediaElementSource(bb).connect(bbf).connect(gb).connect(c.destination);ga.gain.value=1;gb.gain.value=0;ba.gain.value=0;bbf.gain.value=-10;gainA.current=ga;gainB.current=gb;bassA.current=ba;bassB.current=bbf};
 useEffect(()=>{const a=aRef.current;if(!a||!src)return;const path=src.split("?")[0];if(loaded.current!==path){loaded.current=path;transitioning.current=false;a.src=src;a.load();if(playing)a.play().catch(e=>setError(e?.message||"Playback was blocked."))}},[src,playing]);
 useEffect(()=>{const a=audio();if(!a)return;if(playing){try{ensureGraph();ctx.current?.resume()}catch(e){setError(e instanceof Error?e.message:"Web Audio unavailable")}if(a.paused)a.play().catch(e=>setError(e?.message||"Playback was blocked."))}else{aRef.current?.pause();bRef.current?.pause()}},[playing]);
 useEffect(()=>{const clear=()=>{if(timer.current)window.clearTimeout(timer.current);timer.current=null};const a=audio();if(!a||!src||!nextSrc||transitioning.current)return;const schedule=()=>{clear();const bpm=currentBpm&&currentBpm>0?currentBpm:120;const beat=currentBeat&&currentBeat>0?currentBeat:60/bpm;const beats=8;const fade=Math.min(12,Math.max(4,beat*beats));const delay=Math.max(0,(a.duration||0)-a.currentTime-fade);timer.current=window.setTimeout(()=>startTransition(fade,beat),delay*1000)};const startTransition=(fade:number,beat:number)=>{if(transitioning.current||!nextSrc)return;const from=audio(),to=active.current===0?bRef.current:aRef.current;if(!from||!to)return;transitioning.current=true;try{ensureGraph();ctx.current?.resume();to.src=nextSrc;to.load();const ratio=currentBpm&&nextBpm?Math.max(.94,Math.min(1.06,currentBpm/nextBpm)):1;to.playbackRate=ratio;const start=Math.max(0,nextFirstBeat||0);try{to.currentTime=start}catch{}const p=to.play();if(p)p.catch(e=>{setError(e?.message||"Next track could not start");transitioning.current=false;return});const now=ctx.current?.currentTime||0,gFrom=active.current===0?gainA.current:gainB.current,gTo=active.current===0?gainB.current:gainA.current,bFrom=active.current===0?bassA.current:bassB.current,bTo=active.current===0?bassB.current:bassA.current;gFrom?.gain.cancelScheduledValues(now);gTo?.gain.cancelScheduledValues(now);bFrom?.gain.cancelScheduledValues(now);bTo?.gain.cancelScheduledValues(now);gFrom?.gain.setValueAtTime(1,now);gTo?.gain.setValueAtTime(0,now);bFrom?.gain.setValueAtTime(0,now);bTo?.gain.setValueAtTime(-10,now);gFrom?.gain.setValueCurveAtTime(new Float32Array([1,.96,.8,.58,.3,0]),now,fade);gTo?.gain.setValueCurveAtTime(new Float32Array([0,.04,.2,.42,.7,1]),now,fade);bFrom?.gain.setValueCurveAtTime(new Float32Array([0,-1,-3,-6,-9,-10]),now,fade);bTo?.gain.setValueCurveAtTime(new Float32Array([-10,-9,-6,-3,-1,0]),now,fade);window.setTimeout(()=>{from.pause();from.currentTime=0;active.current=active.current===0?1:0;loaded.current=nextSrc.split("?")[0];transitioning.current=false;endRef.current()},fade*1000)}catch(e){setError(e instanceof Error?e.message:"Transition failed");transitioning.current=false}};if(Number.isFinite(a.duration)&&a.duration>0)schedule();else a.addEventListener("loadedmetadata",schedule,{once:true});return clear},[src,nextSrc,currentBpm,nextBpm,currentBeat,nextBeat,nextFirstBeat,currentEnergy,nextEnergy]);
 useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current);ctx.current?.close()},[]);
 return <div>{error&&<div style={{color:"#ff7777",fontSize:11,marginBottom:6}}>{error}</div>}<audio ref={aRef} controls preload="metadata" playsInline className="audio-player"/><audio ref={bRef} preload="metadata" playsInline style={{display:"none"}}/></div>
}