"use client";
import{useEffect,useMemo,useState}from"react";import AudioPlayer from"./audio-player";
type Track={id:string;title:string;artist?:string;key:string;sourceUrl?:string;audioUrl:string;addedAt:number;bpm?:number;duration?:number;analysis?:{energy?:number}};type DJ={running:boolean;current:{id:string;title:string;artist?:string}|null;queue:{id:string;title:string;artist?:string}[];history:Record<string,number>;updatedAt:number};
async function djApi(action:string,extra:any={}){const r=await fetch("/api/dj",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...extra})});return r.json()}
export default function Home(){const[library,setLibrary]=useState<Track[]>([]),[dj,setDj]=useState<DJ>({running:false,current:null,queue:[],history:{},updatedAt:0}),[title,setTitle]=useState(""),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("Library ready.");
async function load(){const[r1,r2]=await Promise.all([fetch("/api/library",{cache:"no-store"}),fetch("/api/dj",{cache:"no-store"})]);const a=await r1.json(),b=await r2.json();if(r1.ok)setLibrary(a.tracks||[]);if(r2.ok)setDj(b)}
useEffect(()=>{load();const i=setInterval(load,3000);return()=>clearInterval(i)},[]);
const catalog=useMemo(()=>library.map(t=>({id:t.id,title:t.title,artist:t.artist})),[library]);const current=library.find(t=>t.id===dj.current?.id)||null;const shown=library.filter(t=>`${t.title} ${t.artist||""}`.toLowerCase().includes(q.toLowerCase()));
async function act(action:string,track?:Track){const n=await djApi(action,track?{track,catalog}:{catalog});setDj(n)}

async function uploadFiles(files:FileList|File[]){const list=Array.from(files);if(!list.length)return;setBusy(true);let done=0;try{for(const f of list){if(!/\.(mp3|wav)$/i.test(f.name)){setNotice(`Skipped unsupported file: ${f.name}`);continue}setNotice(`Preparing ${f.name}…`);const r=await fetch("/api/library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"presign",filename:f.name})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`Could not prepare ${f.name}`);setNotice(`Uploading ${f.name} — 0%`);await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();const timer=window.setTimeout(()=>{x.abort();reject(new Error(`R2 upload timed out for ${f.name}. Check R2 CORS/settings.`))},120000);x.open("PUT",p.uploadUrl,true);x.setRequestHeader("Content-Type",p.contentType);x.upload.onprogress=e=>{if(e.lengthComputable)setNotice(`Uploading ${f.name} — ${Math.round(e.loaded/e.total*100)}%`)};x.onload=()=>{clearTimeout(timer);if(x.status>=200&&x.status<300)resolve();else reject(new Error(`R2 upload failed for ${f.name} (HTTP ${x.status})`))};x.onerror=()=>{clearTimeout(timer);reject(new Error(`R2 upload was blocked or failed for ${f.name}. Check R2 CORS.`))};x.onabort=()=>{clearTimeout(timer);reject(new Error(`R2 upload timed out for ${f.name}`))};x.send(f)});const name=f.name.replace(/\.(mp3|wav)$/i,"").replace(/[-_]+/g," ");setNotice(`Saving ${f.name} to Library…`);const z=await fetch("/api/library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"finalize",track:{id:p.id,key:p.key,title:name,addedAt:Date.now()}})});const d=await z.json().catch(()=>({}));if(!z.ok)throw new Error(d.error||`Could not save ${f.name} to Library`);setLibrary(d.tracks||[]);done++}setNotice(`${done} file${done===1?"":"s"} added to Library.`)}catch(e){setNotice(e instanceof Error?e.message:"Upload failed.")}finally{setBusy(false)}}
async function remove(id:string){if(!confirm("Delete this track from the library?"))return;const r=await fetch("/api/library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id})}),d=await r.json();if(r.ok)setLibrary(d.tracks||[])}
return <main><header className="topbar"><div className="brand"><span className="brandmark">MX</span><div><b>MIXODJ</b><small>AUTONOMOUS DJ · R2 MUSIC LIBRARY</small></div></div><div className={dj.running?"live liveOn":"live"}><i/> {dj.running?"AUTO DJ ACTIVE":"STOPPED"}</div></header>
<section className="hero"><div><p className="eyebrow">UPLOAD · ANALYZE · MIX · PLAY</p><h1>Let the room<br/><em>move itself.</em></h1><p className="sub">Upload your MP3 or WAV files directly. MixoDJ stores them in R2 and builds the Auto-DJ library from your saved music. No YouTube player and no downloader.</p><button className={dj.running?"primary running":"primary"} onClick={async()=>{const n=await djApi(dj.running?"stop":"start",{catalog});setDj(n)}}>{dj.running?"■ STOP AUTO DJ":"▶ START AUTO DJ"}</button></div>
<div className="deck"><div className="decktop"><span>NOW PLAYING</span><span>{current?"LOCAL MP3":"NO TRACK"}</span></div><div className="wave">{Array.from({length:18},(_,i)=><span key={i}/>)}</div><h2>{current?.title||"Nothing playing"}</h2><p>{current?.artist||"Start Auto DJ or choose a library track"}</p><AudioPlayer src={current?.audioUrl||null} playing={dj.running&&!!current} onEnded={()=>act("syncEnded")}/><div className="meters"><div><label>LIBRARY</label><b>{library.length}</b></div><div><label>QUEUE</label><b>{dj.queue.length}</b></div><div><label>NEXT</label><b>{dj.queue[0]?.title||"AUTO SELECT"}</b></div></div></div></section>
<section className="states"><div className="sectionhead"><div><span className="eyebrow">MUSIC LIBRARY</span><h3>Saved music</h3></div><span className="muted">{library.length} tracks</span></div>
<div className="import"><label className="upload-button">UPLOAD MP3 / WAV<input hidden multiple type="file" accept=".mp3,.wav,audio/mpeg,audio/wav" onChange={e=>{if(e.target.files)uploadFiles(e.target.files)}}/></label><span className="hint">{busy?"Uploading…":"Select multiple music files at once"}</span></div><div className="import"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Optional note (future metadata)"/><span className="hint">Track names are taken from filenames for now.</span></div>
<div className="library-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search saved music…"/><span>{shown.length} shown</span></div>
<div className="library">{shown.map((t,i)=><div className="track" key={t.id}><span className="num">{String(i+1).padStart(2,"0")}</span><div><b>{t.title}</b><small>{t.artist||"MP3"} · saved {new Date(t.addedAt).toLocaleDateString()}</small></div><button className="small-action" onClick={()=>act("playNow",t)}>▶ PLAY</button><button className="small-action" onClick={()=>act("add",t)}>+ QUEUE</button><button className="delete-action" onClick={()=>remove(t.id)}>×</button></div>)}{!shown.length&&<p className="notice">No saved music yet.</p>}</div></section>
<section className="grid"><div className="panel"><div className="sectionhead"><div><span className="eyebrow">UP NEXT</span><h3>DJ queue</h3></div><button className="ghost" onClick={()=>act("next")}>SKIP →</button></div>{dj.queue.map((t,i)=><div className="track" key={t.id}><span className="num">{String(i+1).padStart(2,"0")}</span><div><b>{t.title}</b><small>{t.artist||"Library"}</small></div><span className="tag">QUEUED</span></div>)}{!dj.queue.length&&<p className="notice">Auto DJ selects from your saved Library.</p>}</div>
<div className="panel"><span className="eyebrow">AUDIO PIPELINE</span><h3>UPLOAD → R2 → AUTO DJ</h3><p className="hint">The YouTube URL is never used for playback. The DJ reads the saved MP3 from R2 through the normal HTML5 audio engine.</p><div className="pipeline"><span>UPLOAD</span><i>→</i><span>R2</span><i>→</i><span>ANALYZE</span><i>→</i><span>MIX</span></div><p className="notice">{notice}</p></div></section>
<footer><span>MIXODJ / AUTONOMOUS MUSIC SYSTEM</span><span>DATABASE-FREE · R2 LIBRARY · 24H REPEAT PROTECTION</span></footer></main>}